frameless-runtime/src/lib.rs
Tuxedo does not yet have any real PoS- or even PoA- style authority set management pieces. So for now we use simple hard-coded authority sets.
This PR improves this situation slightly by making all of the standard (Alice, Bob, Charlie, etc) keys readily available and providing comments explaining that that's what is happening.
=> Cleanup and explain consensus authority sets

Cargo.lock, frameless-runtime/Cargo.toml, frameless-runtime/src/lib.rs, node/Cargo.toml, node/src/command.rs, node/src/service.rs, tuxedo-core/Cargo.toml
Just a routine Substrate update. Other than changing the version requirement, the only changes are:
* Removed explicit version requirements which are always a pain when updating
* `sp-` and `sc-finality-grandpa` renamed to `sp-` and `sc-consensus-grandpa` (https://github.com/paritytech/substrate/pull/13458)
* Reflect warp sync changes https://github.com/paritytech/substrate/pull/12761
=> Update Substrate to monthly-2023-03

frameless-runtime/src/amoeba.rs, frameless-runtime/src/money.rs, tuxedo-core/src/dynamic_typing.rs
This PR primarily adds tests for the amoeba example piece.
It also fixes one small error that the tests found.
And finally, it moves the `Bogus` type from the money piece to a reusable location in the tuxedo core crate so that it can be used in tests for all pieces.
=> Amoeba tests

.github/workflows/rustdocs.yml, .gitignore
This PR adds a second CI workflow to deploy our rustdocs to github pages for easy reference by developers, grant reviewers, and anyone else.
=> CI: Deploy rustdocs to github pages

tuxedo-core/src/executive.rs, tuxedo-core/src/verifier.rs, tuxedo-template-runtime/src/amoeba.rs, tuxedo-template-runtime/src/kitties.rs, tuxedo-template-runtime/src/lib.rs, tuxedo-template-runtime/src/money.rs, tuxedo-template-runtime/src/poe.rs, tuxedo-template-runtime/src/runtime_upgrade.rs
:warning: This PR is not against `main`; it is against #41 
**Main Change**
The main thing this PR does is add a blanket implementation so that any type that implements the `SimpleVerifier` automatically implements the more powerful `Verifier`. Doing it with a blanket impl avoids the need for a macro.
**Secondary Change**
This slightly changes the signature for the new powerful `Verifier` trait so that it doesn't take inputs, but rather the `Outputs` that are being consumed by the inputs. This allows trait implementers (aka piece developers) not to worry about fetching the Outputs from storage.
=> Blanket impl for powerful verifier

Cargo.lock, tuxedo-core/Cargo.toml, tuxedo-core/src/dynamic_typing.rs, tuxedo-core/src/executive.rs, tuxedo-core/src/redeemer.rs, tuxedo-core/src/types.rs, tuxedo-core/src/utxo_set.rs, tuxedo-core/src/verifier.rs
This PR adds significant test coverage to the `tuxedo-core` crate.
I hope to achieve 100% according to [cargo tarpaulin](https://lib.rs/crates/cargo-tarpaulin), but I'm not sure how practical that is. In any case, this will add enough coverage to give tuxedo users peace of mind that the core code is working as expected.
=> Test tuxedo core

node/src/command.rs
Solves #21.
Updates the copyright start year, the issue queue url and the name of the node.
=> Better branding in command.rs

Cargo.lock, README.md, wallet/Cargo.toml, wallet/README.md, wallet/src/cli.rs, wallet/src/main.rs, wallet/src/money.rs, wallet/src/sync.rs
Aka Joshy's final pass before milestone 2.
This PR:
* Adds a readme with a detailed walkthough in the wallet crate
* Fixes a bug where the wallet would select the same input multiple times for inclusion in a transaction
* Uses `env_logger` and `log` crates for better output logging
* Makes the CLI a little more intuitive
=> Wallet Readme

wallet/src/keystore.rs
Simple PR to add missing doc comments to three functions in the wallet's keystore file
=> Add some missing docs

tuxedo-core/src/verifier.rs
When I was recently preparing the Substrate update in #67, I was briefly confused about the tests on the `ThresholdMultisig`. Once I read the tests carefully, I understood them and quickly got them passing.
However, I noticed that there was not a test for the case where the redeemer contains _more than enough_ valid signatures. This PR adds a single test for when there is a 2/3 multisig, and the redeemer contains valid sigs for _all three_ signatories even though only two are required. I expected this case to still successfully verify, but it seems it is not.
@coax1d is this the behavior you expected?
=> Another multisig test

.github/workflows/docker.yml, Dockerfile
Docker CI normally only runs on `main`. When I merged the aggregation macros PR, it failed on main. I reran a few times over the next few days and it is still failing. IDK why. The log output sounds like the wasm32-unknown-unknown target isn't installed, but it is running in a parity builder image. It is still recommended in the official Substrate repo.
Although the docs around that docker setup have changed a bit. They got removed from the node template repo, but still exist in the main Substrate repo. IDK if that is related to our now-failing CI. I've updated the links in any case.
=> Update dockerfile to match Substrate's

tuxedo-core/src/lib.rs, tuxedo-core/src/traits.rs, tuxedo-template-runtime/src/lib.rs, tuxedo-template-runtime/src/money.rs, wallet/src/money.rs, wallet/src/sync.rs
This PR is replacement for #69 with reduced scope. It also solves #17 by demonstrating that it was always possible :)
This PR extends the money piece to be generic over a `const u8` which is it's token id. The `Coin` type which implements `UtxoData` is also generic over this type so that different coins can be distinguished at the type level when they are pulled back out from storage.
It also introduces a trait called `Cash` which abstracts the notion of a fungible cash-like asset. The `Cash` trait also exposes the token id, although this design may change later.
=> Instantiable Money Piece

Cargo.lock, node/Cargo.toml, node/src/service.rs, tuxedo-core/Cargo.toml, tuxedo-core/src/dynamic_typing.rs, tuxedo-core/src/types.rs, tuxedo-core/src/verifier.rs, tuxedo-template-runtime/Cargo.toml, tuxedo-template-runtime/src/amoeba.rs, tuxedo-template-runtime/src/lib.rs, tuxedo-template-runtime/src/poe.rs, tuxedo-template-runtime/src/runtime_upgrade.rs, wallet/Cargo.toml
This PR updates most of our dependencies, most significantly Substrate.
I couldn't update jsonrpsee because Substrate itself hasn't done so yet.
The biggest change is that the `Block` type has to implement `TypeInfo` now, so a lot of our types throughout the core, runtime, and pieces, now also implement `TypeInfo`.
=> Update Substrate and other dependencies

Cargo.lock, Cargo.toml, node/Cargo.toml, tuxedo-core/Cargo.toml, tuxedo-core/aggregator/Cargo.toml, tuxedo-core/no_bound/Cargo.toml, tuxedo-template-runtime/Cargo.toml, wallet/Cargo.toml, wallet/src/sync.rs, wardrobe/amoeba/Cargo.toml, wardrobe/kitties/Cargo.toml, wardrobe/money/Cargo.toml, wardrobe/poe/Cargo.toml, wardrobe/runtime_upgrade/Cargo.toml
=> Use Workspace Dependencies

wardrobe/poe/src/lib.rs
This PR removes some manual `Clone` and `Debug` implementations from the Proof of Existence piece. These impls were written before the no bound derive macros were introduced.
=> Poe piece: Use derive NoBound macros instead of manual impls

tuxedo-core/src/executive.rs, tuxedo-template-runtime/src/lib.rs
This small PR changes the way we calculate extrinsics roots to use state version 0 instead of 1. Previously I was just using `V1` because I figured we should use the newest thing.
However, Substrate's networking code uses `V0` and we need to match it or else blocks with extrinsics will not import correctly on other nodes.
https://github.com/paritytech/polkadot-sdk/blob/945ebbbcf66646be13d5b1d1bc26c8b0d3296d9e/substrate/client/network/sync/src/lib.rs#L2415
I discovered this while working on #100 and decided to extract it to its own specific PR
=> Extrinsics root must use `StateVersion::V0`

tuxedo-core/src/types.rs
This doc string probably got dropped in a botched merge or something. This just brings it back.
=> Restore doc for transaction inputs

.github/workflows/ci.yml
This small PR remove the installation of protoc when running rust fmt. I believe it is not necessary there. But if I'm wrong CI will tell me :)
=> Remove protobuf installation from rustfmt CI

Dockerfile, wallet/src/main.rs
There was a change in Substrate at some point so that port 9933 is no longer the default for http. In fact it is no longer used at all. Now both http and ws are on port 9944.
=> Update wallet and dockerfile to reflect everything on port 9944

wallet/src/rpc.rs
Solves #120 (hopefully)
I'm not sure exactly when or why something changed in jsonrpsee or some other dependency and the wallet could no longer decode structured blocks from the RPC's json response.
This PR works around the issue by having the wallet first decode the json into an opaque block, and then get a structured block by making a round trip encode/decode to scale bytes.
I'm not sure if there is a more efficient or elegant way to get a structured block on the wallet side, but this is the only thing I could figure out to make the wallet work again.
=> Update wallet to work with new RPC responses.

.github/workflows/ci.yml, README.md
While reviewing #100 I noticed that aforesaid feature silently introduced in #113 does not work.
I hope switching to this other fork of the action will fix it, without introducing other problems.
=> make CI delete old comments

Cargo.lock, Cargo.toml, tuxedo-core/Cargo.toml, tuxedo-core/src/dynamic_typing.rs, tuxedo-core/src/types.rs, tuxedo-core/src/verifier.rs, tuxedo-template-runtime/Cargo.toml, tuxedo-template-runtime/build.rs, tuxedo-template-runtime/src/lib.rs, wardrobe/amoeba/Cargo.toml, wardrobe/amoeba/src/lib.rs, wardrobe/kitties/Cargo.toml, wardrobe/kitties/src/lib.rs, wardrobe/money/Cargo.toml, wardrobe/money/src/lib.rs, wardrobe/poe/Cargo.toml, wardrobe/poe/src/lib.rs, wardrobe/runtime_upgrade/Cargo.toml, wardrobe/runtime_upgrade/src/lib.rs, wardrobe/timestamp/Cargo.toml, wardrobe/timestamp/src/lib.rs
Previously, we only derived `Serialize` and `Deserialize` when building to `std`. This used to be common practice in Substrate, but it has changed now, as suggested in https://github.com/Off-Narrative-Labs/Tuxedo/pull/130#issuecomment-1765336061.
This PR updates the Tuxedo code to derive these traits in both targets. In doing so, it updates serde and enables the serde feature in a few Substrate core crates.
=> Derive serde traits in `no_std` too

.github/workflows/ci.yml, wallet/src/cli.rs, wallet/src/keystore.rs, wallet/src/main.rs, wallet/test.sh
closes #133 
- default key Shawn is not included in the keystore anymore 
- it is only included when the `--dev` arg is set
- arg `--tmp` will clear the data folder at the end. `--dev` enables `--tmp` under the hood.
I also improved some documentation here and there, mostly added `verbatim_doc_comment` to show the entire doc comment and support newlines.
=> implement `--tmp` and `--dev` for wallet

Cargo.lock, Cargo.toml, README.md, node/Cargo.toml
Use ParityDB as the default database, and allow RocksDB to be used by compiling the node with the feature flag `rocksdb`.
This was done because building RocksDB is only a waste of time and resources if used for CI and tests.
=> `rocksdb` feature flag

wardrobe/timestamp/src/lib.rs
This PR makes a small change to the way the genesis timestamp inherent extrinsic is generated. Previously we put in the true wall-clock timestamp at the moment that the genesis block was generated.
The problem was that when starting a new local testing chain, block 1 could be authored so soon after the genesis block was created that it failed the runtime's minimum elapsed time checks. 
Shoutout to @muraca for finding this subtle problem. It was actually a race condition and sometimes, including in CI, the issue wouldn't happen.
In the end there may be a nicer solution, but it is important to me to get this fixed to unblock the parachain work, so we do this for now. Some other solutions we considered.
1. Add a sleep when starting a dev node (it won't happen on a production chain, because …
=> Subtract offset from genesis timestamp

Cargo.lock, Cargo.toml
Second try to update to v1.3.0 after #141 changed in scope.
This uses the next commit on the release branch instead of the tag itself.
Thanks to https://substrate.stackexchange.com/questions/10488/compile-error-in-vandersnatch-vrfs-crate-in-sdk-version-1-3-0 for the help.
=> Update SDK to v1.3.0 (release branch)

tuxedo-core/src/verifier.rs, tuxedo-template-runtime/src/genesis.rs, tuxedo-template-runtime/src/lib.rs, wallet/src/main.rs, wallet/src/money.rs, wallet/src/output_filter.rs, wallet/src/sync.rs
=> renamed `SigCheck` to `Sr25519Signature`

tuxedo-template-runtime/src/lib.rs, wallet/src/cli.rs, wallet/src/main.rs, wallet/src/money.rs, wallet/src/sync.rs, wallet/src/timestamp.rs
This is useful to check that #151 is working as expected.
=> added timestamp to wallet

Cargo.lock, Cargo.toml, parachain-node/Cargo.toml
Closes #154 
I hoped it would close PR #155 too, but it isn't enough.
This PR switches our SDK dependency to a branch that already has https://github.com/paritytech/polkadot-sdk/pull/2553 cherry-picked in. This removes the dependency on rocks-db from the repo.
This will save lots of compile time and disk including in CI where we are currently overloading the disk.
=> Re-Remove rocks db dependency

wallet/README.md, wallet/src/cli.rs, wallet/src/main.rs, wallet/src/money.rs
mint-coins functionality is added this is w.r.t below issue .
https://github.com/Off-Narrative-Labs/Tuxedo/issues/163
With this functionality, it is possible to mint the coins via wallet. Below is the spec:
1. We can optionally pass the amount and public key of the owner as arguments to mint-coins.
2. If optional arguments are not passed, below are the default values:
a. The amount is 100 coin
b. owner(public key) is 0xd2bf4b844dfefd6772a8843e669f943408966a977e3ae2af1dd78e0f55f4df67 i.e SHAWN_PUB_KEY
<details>
<summary>Below are test results :</summary>
Case 1: mint the coin passing both args amount and owner
$ ./target/release/tuxedo-template-wallet mint-coins --owner 0xa6a765bff24ed7cb5d6ac9875a07fe991d96e017611e0e73d70111fe3124f628 --amount 800 
[2024-01-16T09:17:00Z INFO …
=> Wallet: mint-coins functionality

parachain-node/src/rpc.rs, tuxedo-core/src/inherents.rs
Fixes a couple little clippy lints that were previously missed.
=> Make clippy CI pass

tuxedo-core/aggregator/src/lib.rs, tuxedo-core/src/executive.rs, tuxedo-core/src/lib.rs, tuxedo-core/src/verifier.rs, wallet/src/keystore.rs, wallet/src/money.rs
This PR fixes a few bugs that were introduced with #172.
Specifically, it fixes two bugs:
1. The wallet was not encoding the new strongly typed redeemers properly. We may be able to skip this encoding entirely in a followup now that we have more strongly typed redeemers. For now, I have got the encoding working again.
2. When checking transactions in the pool (an off-chain call), we were calling for the block number which was not available at that time. I've fixed this by persisting the block number in storage between blocks.
I guess it is even more clear that we need the entire wallet script to run in CI now.
=> Cleanups after Verifier trait overhaul

wallet/src/main.rs, wallet/src/sync.rs
This PR fixes a bug in the wallet that prevented it from properly indexing the timestamp. Previously the timestamp inherent abused the `UpForGrabs` verifier. This verifier was caught by the wallet's output filter, and indexed.
Later in #172 we refactored away from using `UpForGrabs` which silently broke the wallet's timestamp functionality.
This PR changes the wallet to index the timestamp regardless of whether it meets the user's normal output filter.
=> Fix wallet indexing timestamp

tuxedo-core/src/lib.rs, tuxedo-core/src/metadata.rs, tuxedo-parachain-runtime/src/lib.rs, tuxedo-template-runtime/src/lib.rs, wallet/src/cli.rs, wallet/src/main.rs, wallet/src/rpc.rs
This PR starts exploring the tip of the metadata iceburg.
So far we just encode a single bit which indicates whether the chain is the parachain template or the sovereign template. No other chains are supported.
Seems to be working.
=> Simple metadata to distinguish parachain template from standalone template
